Repository NRLMMD-GEOIPS/template_basic_plugin, pull requests merged in 2023-05, with the labels that each got.

#4 Make template_basic_plugin a fully functional plugin repo
  .gitignore
  CHANGELOG.md
  README.md
  VERSION
  docs/pip_install_instructions.rst
  docs/source/releases/index.rst
  docs/source/releases/v0_1_0.rst
  docs/template_instructions.rst
  my_package/__init__.py
  my_package/interface_modules/readers/my_reader.py
  my_package/plugins/__init__.py
  my_package/plugins/modules/__init__.py
  my_package/plugins/modules/algorithms/__init__.py
  my_package/plugins/modules/algorithms/pmw_89test.py
  my_package/plugins/yaml/product_defaults/89-Test.yaml
  my_package/plugins/yaml/products/amsr2_test.yaml
  my_package/yaml_configs/product_inputs/@source_name@.yaml
  my_package/yaml_configs/product_inputs/amsr2.yaml
  my_package/yaml_configs/product_params/89-Test.yaml
  my_package/yaml_configs/product_params/@Product-Name@.yaml
  pyproject.toml
  setup.py
  tests/outputs/amsr2.global_clean.89-Test/20200518.062048.gcom-w1.amsr2.89-Test.global.13p55.star.20p0.png
  tests/outputs/amsr2.global_clean.color37/20200518.062048.gcom-w1.amsr2.color37.global.18p65.star.20p0.png
  tests/outputs/amsr2.tc_clean.89-Test/20200518_073601_IO012020_amsr2_gcom-w1_89-Test_140kts_28p31_1p0-clean.png
  tests/outputs/amsr2.tc_clean.89pct/20200518_073601_IO012020_amsr2_gcom-w1_89pct_140kts_28p31_1p0-clean.png
  tests/scripts/@mydatatype@.tc.@product@.imagery_clean.sh
  tests/scripts/amsr2.global_clean.89-Test.sh
  tests/scripts/amsr2.tc_clean.89-Test.sh
  tests/scripts/test_config.sh
  tests/scripts/test_config.yaml
  tests/test_all.sh
Labels: enhancement, refactor

#5 211- Update products to be compliant with new YAML interface
  CHANGELOG.rst
  README.md
  my_package/plugins/yaml/products/amsr2_test.yaml
  tests/scripts/amsr2.global_clean.89-Test.sh
  tests/scripts/amsr2.tc_clean.89-Test.sh
  tests/test_all.sh
Labels: breaking change

#7 Remove "GEOIPS_CONFIG_FILE" references
  README.md
  docs/pip_install_instructions.rst
  docs/template_instructions.rst
  setup/config_my_package
Labels: documentation

#8 Show examples of family-based and product-defaults-based products and rework comments in plugins
  CHANGELOG.rst
  my_package/plugins/yaml/product_defaults/89-Test.yaml
  my_package/plugins/yaml/product_defaults/89_PCT_Test.yaml
  my_package/plugins/yaml/products/amsr2_fully_specified.yaml
  my_package/plugins/yaml/products/amsr2_product_defaults.yaml
  my_package/plugins/yaml/products/amsr2_test.yaml
  my_package/yaml_configs/product_inputs/amsr2.yaml
  my_package/yaml_configs/product_params/89-Test.yaml
  tests/outputs/amsr2.global_clean.89-PCT-Fully-Specified/20200518.062048.gcom-w1.amsr2.89-PCT-Fully-Specified.global.13p55.star.20p0.png
  tests/outputs/amsr2.global_clean.89-PCT-Product-Defaults/20200518.062048.gcom-w1.amsr2.89-PCT-Product-Defaults.global.13p55.star.20p0.png
  tests/outputs/amsr2.tc_clean.89-PCT-Fully-Specified/20200518_073601_IO012020_amsr2_gcom-w1_89-PCT-Fully-Specified_140kts_28p31_1p0-clean.png
  tests/outputs/amsr2.tc_clean.89-PCT-Product-Defaults/20200518_073601_IO012020_amsr2_gcom-w1_89-PCT-Product-Defaults_140kts_28p31_1p0-clean.png
  tests/scripts/amsr2.global_clean.89-PCT-Product-Defaults.sh
  tests/scripts/amsr2.tc_clean.89-PCT-Fully-Specified.sh
  tests/scripts/test_config.yaml
  tests/test_all.sh
Labels: testing
