Repository NRLMMD-GEOIPS/template_basic_plugin, pull requests merged in 2024-07, with the labels that each got.

#21 v1.12.1 template_basic_plugin - VERSION RELEASE - standardize install
  CHANGELOG.rst
  docs/source/releases/v0_1_0.rst
  my_package/_version.py
  pyproject.toml
  tests/test_all.sh
Labels: Version Release

#22 WORKSHOP add templating options to pyproject.toml
  docs/source/releases/v0_1_0.rst
  pyproject.toml
Labels: bug

#23 WORKSHOP Update LICENSE and all headers
  CHANGELOG.rst
  DISTRIBUTION
  LICENSE
  README.md
  docs/source/introduction/index.rst
  docs/source/my_package_api/index.rst
  docs/source/releases/index.rst
  docs/source/releases/v0_1_0.rst
  docs/source/userguide/index.rst
  docs/source/userguide/template_instructions.rst
  my_package/__init__.py
  my_package/_version.py
  my_package/plugins/__init__.py
  my_package/plugins/modules/__init__.py
  my_package/plugins/modules/algorithms/__init__.py
  my_package/plugins/modules/algorithms/pmw_89test.py
  tests/scripts/amsr2.global_clean.89-PCT-Using-Product-Defaults.sh
  tests/scripts/amsr2.tc_clean.89-PCT-Fully-Specified.sh
  tests/scripts/test_config.sh
  tests/test_all.sh
Labels: bug

#26 fixed error in template_basic_plugin pyproject.toml
  docs/source/releases/latest/20-update-pyproject-depedencies.yaml
  pyproject.toml
  tests/scripts/amsr2.global_clean.89-PCT-Using-Product-Defaults.sh
  tests/scripts/amsr2.tc_clean.89-PCT-Fully-Specified.sh
  tests/scripts/test_config.sh
Labels: bug, documentation
